apiVersion: v1
kind: Service
metadata:
  name: ai-platform-backend
  labels:
    app: ai-platform
    component: backend
spec:
  selector:
    app: ai-platform
    component: backend
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP 