apiVersion: v1
kind: Service
metadata:
  name: ai-platform-frontend
  labels:
    app: ai-platform
    component: frontend
spec:
  selector:
    app: ai-platform
    component: frontend
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: ClusterIP 